version: '2.3'
services:
  htmlcssjs:
    container_name: 'container_htmlcssjs'
    build: ./img_htmlcssjs
    image: img_htmlcssjs 
    #bien mettre image apres le build, pour renommer l'image ainsi built
    ports:
      - 8890:8888
    volumes:
      - ~/git/coding/programming/html:/sites
    runtime: nvidia
    command: tail -F anything
    #the tail command will wait forever for the file anything to appear
